#!/usr/bin/env bash
#Configure Nginx so that its HTTP response contains a custom head
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo sed -i '24i\  add_header X-Served-By $HOSTNAME;\n' /etc/nginx/sites-available/default
sudo service nginx start
sudo nginx -s reload



