#!/usr/bin/env bash
# Bash script that Creates the file /var/run/myscript.pid containing its PID
echo "$$" > /var/run/myscript.pid

terminate() 
{
	echo "I hate the kill command"
	rm "/var/run/myscript.pid"
	exit 0
}
trap 'terminate' SIGTERM


display() 
{
	echo "Y U no love me?!"
}
trap 'display' SIGINT


delete() 
{
	rm "/var/run/myscript.pid"
	exit 0
}
# Register the d_handler function to catch the SIGQUIT signal
trap 'delete' SIGQUIT

while 'true'
do
	echo "To infinity and beyond"
done
